# Generated by Django 6.0.4 on 2026-04-10 22:28

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('total_price', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'USD'), max_digits=12)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passport_number', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=8)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trains.departure')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trains.seat')),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_from', to='stations.station')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings_to', to='stations.station')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.order')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.passenger')),
            ],
        ),
    ]
