# Generated by Django 6.0.4 on 2026-04-08 20:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuration',
            },
        ),
    ]
