# Generated by Django 6.0.4 on 2026-04-11 04:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price_factor', models.DecimalField(decimal_places=3, default=1, max_digits=6)),
                ('features', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('stop_duration', models.DurationField(default=datetime.timedelta)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.connection')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='routes.route')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('route', 'order'), name='routesegment_route_order_uniq')],
                'unique_together': {('route', 'segment', 'order')},
            },
        ),
    ]
