# Generated by Django 6.0.4 on 2026-04-08 20:05
import uuid

import django.db.models.deletion
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models

from apps.trains.models import SeatType, CarType


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('avg_speed_kmh', models.FloatField(validators=[MinValueValidator(0.0)])),
                ('price_factor', models.DecimalField(decimal_places=3, default=Decimal('1.0'), max_digits=6)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trains', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trains.train')),
            ],
            options={
                'ordering': ['date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('car_type', models.CharField(default=CarType.COMMON, choices=CarType.choices, max_length=32)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('price_factor', models.DecimalField(decimal_places=3, default=Decimal('1.0'), max_digits=6)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='trains.train')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('train', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(default=SeatType.COMMON, choices=SeatType.choices, max_length=32)),
                ('price_factor', models.DecimalField(decimal_places=3, default=Decimal('1.0'), max_digits=6)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='trains.car')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('car', 'number')},
            },
        ),
    ]
