# Generated by Django 6.0.4 on 2026-04-11 04:21

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=16, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('avg_speed_kmh', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('price_factor', models.DecimalField(decimal_places=3, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('features', models.JSONField(blank=True, default=dict)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trains', to='routes.route')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Car number')),
                ('car_type', models.CharField(choices=[('common', 'Common'), ('sleeper', 'Sleeper'), ('luxury', 'Luxury'), ('dining', 'Dining'), ('other', 'Other')], default='common', max_length=32)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('price_factor', models.DecimalField(decimal_places=3, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='trains.train')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('seat_type', models.CharField(choices=[('common', 'Common'), ('vip', 'VIP'), ('sleeper', 'Sleeper'), ('other', 'Other')], default='common', max_length=32)),
                ('price_factor', models.DecimalField(decimal_places=3, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='trains.car')),
            ],
            options={
                'ordering': ['number'],
                'constraints': [models.UniqueConstraint(fields=('car', 'number'), name='seat_car_number_uniq')],
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='trains.train')),
            ],
            options={
                'ordering': ['date', 'departure_time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'train'), name='departure_date_train_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(fields=('train', 'number'), name='car_train_number_uniq'),
        ),
    ]
