# Generated by Django 6.0.4 on 2026-04-10 22:28

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('base_price_currency', djmoney.models.fields.CurrencyField(choices=[('USD', 'US Dollar')], default='USD', editable=False, max_length=3)),
                ('base_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10)),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_out', to='stations.station')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_in', to='stations.station')),
            ],
        ),
    ]
