# Generated by Django 6.0.4 on 2026-04-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('station_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_out', to='stations.station')),
                ('station_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_in', to='stations.station')),
            ],
        ),
    ]
